# Generated by Django 6.1.1 on 2026-09-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=25, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('customer_type', models.CharField(choices=[('VIP', 'VIP'), ('REGULAR', 'Regular'), ('PREMIUM', 'Premium')], default='REGULAR', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
