# Generated by Django 6.1.1 on 2026-09-11 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceAppliedPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion_name', models.CharField(help_text='Snapshot of promotion name at purchase time', max_length=150)),
                ('discount_amount', models.DecimalField(decimal_places=2, help_text='Discount given by this promotion', max_digits=12)),
                ('priority', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_promotions', to='invoice.invoice')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invoice.promotion')),
            ],
        ),
    ]
